{% set name = "fps-kernels" %}
{% set version = "0.10.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fps_kernels-{{ version }}.tar.gz
  sha256: 8f7c4ba03c6e5f1a4752fd6d77bb25c7c8c356788b6a058ee5c559e170e84070

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - uv-build
  run:
    - python >={{ python_min }}
    - jupyverse-api >=0.12.0,<0.13.0
    - python-dateutil
    - types-python-dateutil
    - pycrdt >=0.10.3,<0.13.0
    - anyio

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - fps_kernels

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/kernels
  summary: An FPS plugin for the kernels API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/kernels
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
