{% set name = "fps-kernels" %}
{% set version = "0.0.32" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_kernels-{{ version }}.tar.gz
  sha256: ed842b8ab0a95cc307d9afdc3073971018d0c8e5e48769240fe3729210d6a0b7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - fps >=0.0.8,<1.0.0
    - fps-auth >=0.0.30,<1.0.0
    - fps-lab >=0.0.30,<1.0.0
    - pyzmq <23.0.0
    - websockets <11.0.0

test:
  imports:
    - fps_kernels

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/kernels
  summary: An FPS plugin for the kernels API
  keywords: jupyter, server, fastapi, pluggy, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/kernels
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
