{% set name = "fps-kernels" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_kernels-{{ version }}.tar.gz
  sha256: 35d97aa11956acffaec23d0d4ff1bb401a6310db4ac2d7023eef959ac87c9d2d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - jupyverse-api >=0.1.4,<1
    - pyzmq
    - websockets
    - python-dateutil
    - watchfiles >=0.16.1,<1

test:
  imports:
    - fps_kernels

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/kernels
  summary: An FPS plugin for the kernels API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/kernels
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
