schema_version: 1

context:
  version: "0.10.11"

package:
  name: fps-kernels
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/f/fps-kernels/fps_kernels-${{ version }}.tar.gz
    sha256: f53bea3693bd5e8dc768ec5f77adec6294b8053718e77bdca7595ab5edb99379

build:
  noarch: python
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build
  run:
    - python >=${{ python_min }}
    - jupyverse-api >=0.14.1,<0.15.0
    - python-dateutil
    - types-python-dateutil

tests:
  - python:
      imports: fps_kernels
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: BSD-3-Clause
  license_file: COPYING.md
  homepage: https://github.com/jupyter-server/jupyverse/tree/main/plugins/kernels
  summary: An FPS plugin for the kernels API

extra:
  recipe-maintainers:
    - davidbrochart
